### ISSUE TITLE
前台—账户中心—我的借款—自动还款功能异常

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#691]
测试场景：自动还款
测试数据库：hermes_test23
借款编号：201505120003

自动还款规则：还款日第二天凌晨1点跑前一天需还款的债权
如：7-1号需还款,7-2日凌晨1点跑timer，自动还款

测试：
此债权7-1号为第二期还款日，手动将系统时间改为2015-7-2 凌晨1点
预期结果：正常还款
实际结果：等待还款

**Comment by huyingjlfex** [comment]
日志：
2015-07-02 01:00:00,040 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-4] INFO  [hermes] - start job 'ScanJlfexWaitOrderJob'
2015-07-02 01:00:00,040 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-3] INFO  [hermes] - start job 'ScanJlfexRepayOrderJob'
2015-07-02 01:00:00,044 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - start job 'AutoBidFailureJob'
2015-07-02 01:00:00,044 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - 批量自动流标 JOB 开始.
2015-07-02 01:00:00,045 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-2] INFO  [hermes] - start job 'AutoChargeQueryJob'
2015-07-02 01:00:00,072 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] WARN  [net.sf.ehcache.config.ConfigurationFactory] - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/root/.m2/repository/net/sf/ehcache/ehcache/2.7.4/ehcache-2.7.4.jar!/ehcache-failsafe.xml
2015-07-02 01:00:00,106 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-4] INFO  [hermes] - 成功完成 job 'ScanJlfexWaitOrderJob', 耗时 '62' 毫秒.
2015-07-02 01:00:00,149 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-3] INFO  [hermes] - 成功完成 job 'ScanJlfexRepayOrderJob', 耗时 '106' 毫秒.
2015-07-02 01:00:00,325 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - initialize ehcache 'consoleDefault' completed.
2015-07-02 01:00:00,325 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - ehcache is ready...
2015-07-02 01:00:00,403 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - set com.jlfex.hermes.cache.loan.bid.list - 0 rows list int cache for 86400 seconds.
2015-07-02 01:00:00,406 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - 自动流标JOB 完成. take 362 毫秒.
2015-07-02 01:00:00,411 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - 成功完成 job 'AutoBidFailureJob', 耗时 '367' 毫秒.
2015-07-02 01:00:01,152 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-2] ERROR [hermes] - 
com.jlfex.hermes.common.exception.ServiceException: @Xbc0r0SDBHFa7G49 null
        at com.jlfex.hermes.service.job.AutoChargeQueryJob.run(AutoChargeQueryJob.java:75)
        at com.jlfex.hermes.service.job.Job.doJob(Job.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
        at com.jlfex.hermes.service.job.AutoChargeQueryJob.run(AutoChargeQueryJob.java:61)
        ... 12 more
2015-07-02 01:00:01,154 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-2] WARN  [hermes] - failure do job 'AutoChargeQueryJob'

**Comment by yanLeiOfJL** [comment]
自动还款规则：02:00执行， 测试场景不对。
