### ISSUE TITLE
前台—账户中心—我的借款—逾期计算job异常

### ISSUE THREAD

**Issue by huyingjlfex** [jlfex/hermes#692]
每天01:50跑逾期计算job

异常日志：
2015-07-02 01:50:00,003 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-2] INFO  [hermes] - start job 'AutoChargeQueryJob'
2015-07-02 01:50:00,008 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - start job 'AutoOverdueCalc'
2015-07-02 01:50:00,008 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-5] INFO  [hermes] - start job 'ScanJlfexWaitOrderJob'
2015-07-02 01:50:00,008 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - 自动逾期计算JOB开始.....
2015-07-02 01:50:00,070 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-5] INFO  [hermes] - 成功完成 job 'ScanJlfexWaitOrderJob', 耗时 '62' 毫秒.
2015-07-02 01:50:00,120 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - 自动逾期计算JOB完成. 耗时  112 millisecond.
2015-07-02 01:50:00,120 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-1] INFO  [hermes] - 成功完成 job 'AutoOverdueCalc', 耗时 '112' 毫秒.
2015-07-02 01:50:00,908 [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor#6369dec4-2] ERROR [hermes] - 
com.jlfex.hermes.common.exception.ServiceException: @crFWyRunKDOsNsT5 null
        at com.jlfex.hermes.service.job.AutoChargeQueryJob.run(AutoChargeQueryJob.java:75)
        at com.jlfex.hermes.service.job.Job.doJob(Job.java:19)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:311)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:113)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
        at com.jlfex.hermes.service.job.AutoChargeQueryJob.run(AutoChargeQueryJob.java:61)
        ... 11 more

**Comment by yanLeiOfJL** [comment]
测试用例不对。

**Comment by huyingjlfex** [comment]
查找自动还款的失败状态的单，每天凌晨01:50分计算，等下个还款日的第二天凌晨02:00跑自动还款
